### ISSUE TITLE
[Suggestion]: Please update to 1.20.2

### ISSUE THREAD

**Issue by jurohn** [Fuzss/horseexpert#9]
### Suggestion (Required)

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Horse Expert' (horseexpert) 8.1.1 with any version that is compatible with:
		 - minecraft 1.20.2
More details:
	 - Mod 'Horse Expert' (horseexpert) 8.1.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.2!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Fuzss** [comment]
Please do not ask for mod updates or ports, they will come when they are ready.
